version: "3.8"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  fastapi:
    build: .
    ports:
      - 8000:8000
    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo

  worker:
    build: .
    entrypoint: arq src.tasks.worker.WorkerSettings
    depends_on:
      - redis
      
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
