version: "3.8"

services:

  redis:
    image: redis:latest
    container_name: ${REDIS_NAME}
    environment: 
      - TZ=${TZ}
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  fastapi:
    build: .
    restart: always
    environment: 
      - TZ=${TZ}
    ports:
      - ${UVICORN_PORT}:8000
    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo

  worker:
    build: .
    restart: always
    environment: 
      - TZ=${TZ}
    entrypoint: arq src.tasks.worker.WorkerSettings
    depends_on:
      - redis
      
  mongo:
    image: mongo:latest
    container_name: ${MONGO_NAME}
    restart: always
    environment: 
      - TZ=${TZ}
    ports:
      - ${MONGO_PORT}:27017
