version: "3.8"

services:

  rabbit:
    image: rabbitmq:latest

  fastapi:
    build: .
    ports:
      - 8000:8000
    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo

  worker:
    build: .
    command: >
      bash -c "celery -A src.tasks beat --loglevel=info
      && celery -A src.tasks worker -c 2 --loglevel=info"
    depends_on:
      - rabbit

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
